
format = """
$time\
$directory\
$kubernetes\
$nodejs\
$python\
$helm\
$terraform\
$rust\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shell\
$character"""

[python]
format = '[$symbol($virtualenv $version )]($style)'

[terraform]
format = '[$symbol($version )]($style)'

[helm]
format = '[$symbol($version )]($style)'

[time]
disabled = false
time_format = '%T'
format = '[$time UTC ]($style)'
utc_time_offset = '0'

[directory]
style = '#3399FF bold'

[git_branch]
style = '#a37acc bold'
format = '[$symbol$branch(:$remote_branch)]($style) '

[kubernetes]
format = '[⛵ ($cluster) ]($style)'

[nodejs]
format = '[$symbol($version)]($style) '

[rust]
format = '[🦀 $version](red bold) '

