- name: Provision on KVM
  hosts: saltmine
  become: true
  vars:
    script_path: "/kvmpool/scripts/fedora"
  tasks:
    - name: Ensure script directory exists
      ansible.builtin.file:
        path: "{{ script_path }}"
        state: directory
        mode: "0755"
    - name: Copy provisioning files
      copy:
        src: "{{ item.src }}"
        dest: "{{ script_path }}/{{ item.dest | default(item.src | basename) }}"
        mode: "0755"
      loop:
        - { src: ./cloud-init.sh }
        - { src: ./user-data.yml }
        - { src: ./meta-data.yml }
        - { src: ./teardown.sh }

    - name: Run cloud-init script
      ansible.builtin.shell: "{{ script_path }}/cloud-init.sh"
      args:
        executable: /bin/bash
