# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: "Checkout"
       uses: actions/checkout@v2

     - name: Run the installer command
       run: ./installer.sh
       
     - name: Is starship linked?
       run: |
         [[ -L ~/.config/starship.toml ]]

     - name: Is .hushlogin present?
       run: |
         [[ -f ~/.hushlogin ]]

     - name: Is .zshrc linked?
       run: |
         [[ -L ~/.zshrc ]]
